### PR TITLE
Basic for parsing/interpreting

### LINKED ISSUE #31: Implement visit_For
It had a TODO in the code

I had fun fiddling with your project! It is magical to see such a small code base to all the magic!

I must say it is not easy to implement everything properly.

Here is my attempt at it :-)

```python
    def visit_For(self, node: For) -> None:
        if len(node.iterable) == 1:
            elements = self.visit(node.iterable[0])
        else:
            elements = [self.visit(e) for e in node.iterable]
        for element in elements:
            value = element
            if len(node.target) > 1:
                # todo must be tuple? (or can it be list too?)
                if len(node.target) > len(value._data):
                    raise Exception(f"ValueError: too many values to unpack (expected {len(node.target)})")
                for idx, t in enumerate(node.target):
                    if isinstance(t, Name):
                        self.scope.set(t.id, value._data[idx])       
            else:
                target = node.target[0]
                if isinstance(target, Name):
                    self.scope.set(target.id, value)
            for stmt in node.body:
                try:
                    self.visit(stmt)
                except Break:
                    return
                except Continue:
                    break
```

I also added the `enumerate` function:

```python
class Enumerate(Function):
    def as_string(self) -> str:
        return "<function 'enumerate'>"

    def arg_count(self) -> int:
        return 1

    def call(self, _: Interpreter, args: list[Object]) -> Object:
        super().ensure_args(args)
        for idx, val in enumerate(args[0]):
            yield Tuple([Value(idx), val])
```

I also added some other code to make the following work:

```python
dct = {
    "one": 1,
    "two": 2
}
def test_dict_items():
    for k,v in dct.items():
        print(k, v)

def test_literal():
    for e in [1,2]:
        print(e)

def test_dict():
    for k in dct:
        print(k, dct[k])

def test_enumerate():
    for idx, tup in enumerate(dct):
        print(idx, tup)

lst = []
lst.append('test')
lst.append('test123')

def test_list():
    for e in lst:
        print(e)

def fnc(a):
    return 1

test_dict_items()
test_literal()
test_dict()
test_enumerate()
test_list()
print(fnc(2))

for x in 1, 2:
    print(x)

for k in dct.items():
    print(k)

tpl = (0, 3)
print(len(tpl))
```

### PR DESCRIPTION
**Pull request by Jacco**
Resolved #31

Also implements __iter__ on Dict and List
added main handling on interpreter
Added enumerate global function
Added items function on Dict
tests also check real python

### CODE REVIEW

**Comment by tusharsadhwani** [comment]
Thanks a lot! Most of the work seems good, especially in the `Interpreter` class.

The parser will probably require some changes, as I think we should reuse `parse_expression()` for the parsing of the `targets` here.

Consider this example from Python's AST:

```console
$ python -m ast <<<'for i in x in y in z: ...'
Module(
   body=[
      For(
         target=Name(id='i', ctx=Store()),
         iter=Compare(
            left=Name(id='x', ctx=Load()),
            ops=[
               In(),
               In()],
            comparators=[
               Name(id='y', ctx=Load()),
               Name(id='z', ctx=Load())]),
         body=[
            Expr(
               value=Constant(value=Ellipsis))],
         orelse=[])],
   type_ignores=[])
```

This seems to show that we can stop at the first `in` statement for the `target`, right?

Well, unfortunately that's not the case, for example, if there are commas after that sub-expression:

```console
$ python -m ast <<<'for i in x, j in y in z: ...'
Module(
   body=[
      For(
         target=Name(id='i', ctx=Store()),
         iter=Tuple(
            elts=[
               Name(id='x', ctx=Load()),
               Compare(
                  left=Name(id='j', ctx=Load()),
                  ops=[
                     In(),
                     In()],
                  comparators=[
                     Name(id='y', ctx=Load()),
                     Name(id='z', ctx=Load())])],
            ctx=Load()),
         body=[
            Expr(
               value=Constant(value=Ellipsis))],
         orelse=[])],
   type_ignores=[])
```

Here, `i in x, j` became the target and `y, z` became the iterable.

Doing this correctly will require some more looking into how Python's actual grammar works.

**Comment by Jacco** [comment]
I did experiment with multiple expressions separated by comma after the in. I think that already works.

The extra ins are comparisson operators or am I missing something :-)

**Comment by tusharsadhwani** [comment]
You're right, I confused myself.

Making some small changes to the code...

**Comment by Jacco** [comment]
I think I also forgot to add the 'range' function

**Comment by tusharsadhwani** [comment]
I made some adjustments:
- Since we don't have a `Generator` type yet, `Items` and `Enumerate` will return a `List` instead. Unfortunate but it is how it is for now.
- The parser was mostly good! I just made sure that `iterable` and `target` were always a `Node`, instead of a list of `Node`s
- Added a parser test to ensure we parse `for` loops properly.

**Comment by tusharsadhwani** [comment]
Please feel free to add a `range` class as well.

**Comment by Jacco** [comment]
> * The parser was mostly good! I just made sure that `iterable` and `target` were always a `Node`, instead of a list of `Node`s

I think they can have multiple. There are examples in the tests:

This one has two targets
```
for k,w in dct.item():
    print(k,w)
```

**Comment by tusharsadhwani** [comment]
> This one has two targets
> 
> ```
> for k,w in dct.item():
>     print(k,w)
> ```

@Jacco In this case `target` will be a `Tuple`, check `parser_test.py` changes.

**Comment by Jacco** [comment]
Ah ok, I missed the inner workings self.assign :-)

**Comment by tusharsadhwani** [comment]
I'll merge this PR soon, you can add a `range` function in a separate one.

**Pull request merged**
